export const slides = [
  {
    id: 'hero',
    tag: null,
    title: ['The Future of', 'Learning is', 'Intelligent'],
    titleAccent: [false, false, true],
    bullets: null,
    accent: '#7C5CFC',
    sub: 'AI-Powered Educational Platform · Web & Mobile · Voice Interaction · n8n Automation',
  },
  {
    id: 'problem',
    tag: '01 · Problem Statement',
    title: ['Why Traditional', 'Education Fails'],
    accent: '#FF4D6D',
    bullets: [
      '📄 Manual paper registration — errors, delays, data loss',
      '📊 Excel scheduling — breaks under any scale',
      '🚫 Zero out-of-class support for students',
      '📚 One-size-fits-all content — students fall behind',
      '🌐 Remote learners have no structure or tracking',
      '🏛️ Admins drown in manual reporting',
      '💸 Fixed schedules price out most learners',
      '🤝 Limited communication between students & instructors',
      '🌍 Social & cultural barriers restrict participation',
    ],
  },
  {
    id: 'opportunities',
    tag: '02 · Opportunities',
    title: ['The Gap We', 'Are Filling'],
    accent: '#00D9B1',
    bullets: [
      '🚀 Digital transformation wave in education sector',
      '🧠 AI enables personalized learning paths at scale',
      '💬 Smart communication tools for continuous interaction',
      '🌐 Structured support for remote & flexible learners',
      '📈 Data-driven analytics for better academic decisions',
      '💰 Reduced costs & flexible scheduling for wider reach',
      '🤲 Inclusivity — break social & cultural learning barriers',
      '🔬 Adaptive assessments + intelligent feedback loops',
    ],
  },
  {
    id: 'objectives',
    tag: '03 · Objectives',
    title: ['What We Set', 'Out to Build'],
    accent: '#7C5CFC',
    bullets: [
      '✦ Develop a unified AI-based teaching platform',
      '✦ Deliver personalized, adaptive learning paths',
      '✦ Ensure 24/7 access — no time barriers',
      '✦ Automate all administrative workflows via n8n',
      '✦ Support web + mobile with offline access',
      '✦ Break social & geographic learning barriers',
      '✦ Reduce cost — $30/month makes it accessible',
      '✦ Integrate modern tools: adaptive assessments & smart feedback',
      '✦ Seamless cross-device learning experience',
    ],
  },
  {
    id: 'significance',
    tag: '04 · Project Significance',
    title: ['Why This', 'Matters'],
    accent: '#FFB347',
    bullets: [
      '♾️ Redefines education — from fixed schedules to fully adaptive',
      '🎯 Personalized lessons tailored to each learner level & style',
      '⏰ 24/7 availability removes all classroom time limitations',
      '⚙️ Automates scheduling, reporting & performance monitoring',
      '💵 Lowers operational costs — education becomes truly affordable',
      '🏗️ Breaks social & cultural barriers to learning access',
      '🔭 Positions AI as a central force in the future of education',
    ],
  },
  {
    id: 'methodology',
    tag: '05 · Methodology',
    title: ['Hybrid SDLC', '+ Agile'],
    accent: '#FFB347',
    bullets: [
      '① Planning — Feasibility, stakeholder mapping, scope definition',
      '② Requirements — Interviews, observation, document analysis',
      '③ Design — Architecture, UML, ERD, DFD, n8n flows, UI/UX',
      '④ Sprint 1 — AI lesson delivery via ChatGPT API',
      '⑤ Sprint 2 — Adaptive assessments + instant feedback',
      '⑥ Sprint 3 — Student & admin dashboards',
      '⑦ Sprint 4 — Full automation, reporting & final testing',
    ],
  },
  {
    id: 'tech',
    tag: '06 · Tech Stack',
    title: ['Built on', 'Modern Tools'],
    accent: '#00D9B1',
    bullets: [
      '⚛️ React 18 + Vite — fast, modern web frontend',
      '📱 Flutter + Dart — cross-platform mobile',
      '🟢 Node.js + Express — RESTful backend',
      '🐍 Python — AI processing layer',
      '🔥 Firebase + Mongodb — cloud database',
      '🔗 n8n Cloud — workflow automation engine',
      '🤖 ChatGPT STT/TTS — voice & intelligence',
    ],
  },
  {
    id: 'feasibility',
    tag: '07 · Feasibility Study',
    title: ['Economically', 'Proven'],
    accent: '#7C5CFC',
    bullets: [
      '💵 Total project cost: $36,700',
      '📈 Year 1 revenue: $43,000 (100 clients × $30/mo)',
      '✅ Year 1 net profit: $6,300 · ROI: 17.2%',
      '📊 Year 2 profit: $20,000 · Year 3: $38,000',
      '🎯 Break-even: ~102 paying clients',
      '⏱️ Payback period: approximately 1 year',
      '🌐 Marketing: Social media + mobile-first SEO',
    ],
  },
  {
    id: 'risks',
    tag: '08 · Risk Analysis',
    title: ['Risks &', 'Mitigations'],
    accent: '#FF4D6D',
    bullets: [
      '🔴 Requirements drift → iterative validation sprints',
      '🔴 Integration bugs (n8n) → early testing + audit logs',
      '🔴 Security breach → AES-256, MFA, audit trails',
      '🟡 Scalability → VPS → AWS/Azure migration plan',
      '🟡 Team pressure → cross-training + task rotation',
      '🟡 User trust in AI → pilot programs + transparency',
      '🟡 Limited payment systems → multiple payment gateways',
    ],
  },
  {
    id: 'work_plan',
    tag: '09 · Work Plan',
    title: ['Project Timeline', '& Schedule'],
    accent: '#00D9B1',
    bullets: [
      '📅 Phase 1 (Wk 1–2): Planning & stakeholder analysis',
      '📅 Phase 2 (Wk 3–4): Requirements gathering & documentation',
      '📅 Phase 3 (Wk 5–7): System design — UML, ERD, DFD',
      '📅 Phase 4 (Wk 8–10): Sprint 1 — Core AI lesson engine',
      '📅 Phase 5 (Wk 11–13): Sprint 2 & 3 — Assessments & dashboards',
      '📅 Phase 6 (Wk 14–16): Sprint 4 — Automation & integration',
      '📅 Phase 7 (Wk 17–18): Testing, evaluation & final report',
    ],
  },
  {
    id: 'previous_systems',
    tag: '10 · Previous Systems',
    title: ['Existing Platforms', '& Our Edge'],
    accent: '#7C5CFC',
    bullets: [
      '🎓 Coursera — Professional certifications, no AI adaptation',
      '📚 Khan Academy — Free academic base, no personalization engine',
      '🦉 Duolingo — Gamified language learning, very narrow scope',
      '❌ All three: no Arabic voice interaction support',
      '❌ All three: no n8n-powered admin automation',
      '❌ All three: no real-time ChatGPT adaptive tutoring',
      '✅ AIM — AI-native, bilingual, voice-first & fully automated',
    ],
  },
  {
    id: 'data_collection',
    tag: '11 · Data Collection',
    title: ['How We', 'Gathered Data'],
    accent: '#FFB347',
    bullets: [
      '📄 Document Analysis — reviewed existing academic workflows',
      '📄 Analyzed institute forms, schedules & reporting processes',
      '🗣️ Interviews — with instructors & academic staff',
      '🗣️ Key insight: multi-skill placement test 20–30 min needed',
      '👁️ Observation — attended live English & institute classes',
      '👁️ Identified admin bottlenecks & teaching inefficiencies',
      '🔬 All findings validated the 9 core problem areas in scope',
    ],
  },
  {
    id: 'functional_req',
    tag: '12 · Functional Requirements',
    title: ['What the System', 'Must Do'],
    accent: '#7C5CFC',
    bullets: [
      '🔐 FR1 — Auth & Roles: Email/OTP/SSO, RBAC, MFA support',
      '🧠 FR2 — AI Placement: Level test ≤ 10 min, adaptive study plan',
      '📖 FR3 — AI Tutoring: ChatGPT chat, voice Q&A, STT/TTS bilingual',
      '📦 FR4 — Content Mgmt: Upload lessons, videos, quizzes, CDN delivery',
      '📝 FR5 — Assessments: Auto-graded quizzes, AI feedback, certificates',
      '📊 FR6 — Dashboards: Student progress, instructor analytics, admin KPIs',
      '💬 FR7 — Global Chat: Real-time bilingual community forum',
    ],
  },
  {
    id: 'non_functional_req',
    tag: '13 · Non-Functional Requirements',
    title: ['Quality &', 'Constraints'],
    accent: '#FF4D6D',
    bullets: [
      '⚡ NFR1 Performance: Page load ≤ 3s · AI reply ≤ 1.5s · 10K users',
      '🟢 NFR2 Availability: 99.9% uptime · RTO/RPO ≤ 1 hour',
      '🔐 NFR3 Security: TLS 1.2+ · AES-256 at rest · RBAC · Audit logs',
      '🤖 NFR4 AI Safety: Explainable AI · bias monitoring · model versioning',
      '♿ NFR5 Accessibility: WCAG 2.1 AA · Arabic RTL · audio transcripts',
      '🔧 NFR6 Maintainability: CI/CD pipelines · Prometheus/Grafana · modular',
      '💬 NFR7 Chat Quality: Real-time delivery · auth-only · scalable',
    ],
  },
  {
    id: 'dfd_level0',
    tag: '14 · DFD — Level 0',
    title: ['System Context', 'Diagram'],
    accent: '#00D9B1',
    bullets: [
      '👤 Student → submits queries, receives lessons & AI responses',
      '👨‍👩‍👧 Parent → monitors child progress, approves access',
      '🏛️ Admin → manages users, roles, reports & configurations',
      '🔍 Reviewer → audits content quality & academic alignment',
      '🔗 Auth Service, CDN, Voice Processing, n8n automation',
      '💾 AIM Platform Hub → routes all data between actors & services',
      '📡 Outputs: personalized lessons, reports, notifications, feedback',
    ],
  },
  {
    id: 'uml',
    tag: '15 · UML Diagrams',
    title: ['System Models', '& Interactions'],
    accent: '#7C5CFC',
    bullets: [
      '👤 Use Case (Student): login, placement test, lessons, chat, quiz',
      '👨‍🏫 Use Case (Instructor): upload content, review assessments, analytics',
      '🏛️ Use Case (Admin): manage users, generate reports, configure system',
      '🔄 Activity — AI Tutoring: Query → Context → GPT → STT/TTS → Deliver',
      '🔄 Activity — Assessment: Start → Attempt → Auto-Grade → Feedback',
      '🔄 Activity — Login: Input → Validate → MFA Check → Dashboard',
      '📊 Classes: User ◇ Course ◇ Lesson ◇ Assessment ◇ Analytics',
    ],
  },
  {
    id: 'conclusion',
    tag: '16 · Conclusion',
    title: ['A Platform Built', 'to Grow'],
    accent: '#00D9B1',
    bullets: [
      '🎯 Solves 9 real problems in traditional education',
      '💡 Novel: ChatGPT + n8n adaptive learning pipeline',
      '🌍 Built for Arabic-speaking learners in the Middle East',
      '📱 Works on web, mobile, and offline',
      '💰 Viable: 17.2% ROI, 1-year payback period',
      '🚀 Future: multilingual, institutional licensing, marketplace',
      '✅ Technical + economic + operational feasibility confirmed',
    ],
  },
]
